### ISSUE TITLE
ObjectNotFound

### ISSUE THREAD

**Issue by edavur** [causalens/dara#110]
Ouput from terminal on Windows 10 with the git bash shell:
- I am using python 3.9.6 on Windows 10.

 C:\Users\DARA> create-dara-app
create-dara-app : The name "create-dara-app" was not recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if the path is correct (if included), and repeat the process.
In line:1 character:1
+ create-dara-app
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (create-dara-app:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Roman-Kornev** [comment]
Please double-check your Environment Variables in Advanced System Settings and make sure your `C:\<PYTHON_LOCATION>\Scripts` folder is included there.
