### ISSUE TITLE
Purpose? 

### ISSUE THREAD

**Issue by edavur** [causalens/dara#138]
Hello, 
I have followed all the steps of Github and looked at your tool. 
However, it seems that there is nothing that can be applied and I was wondering about the exact purpose of your visualization when I cannot do anything using it?

**Comment by tamara-causalens** [comment]
Hello,

Thank you for reaching out and trying out Dara. We appreciate your feedback and would be happy to provide some clarification regarding the purpose of our application framework.

Dara is a framework designed to enable the creation of web apps in pure Python. It comes with a library of UI components, making it easy to create various apps, from simple dashboards to complex interactive applications. The framework specialises in causality by supporting visualisation and interactivity with causal graphs, helping users gain deeper understanding of cause-and-effect relationships in their data and facilitating informed decision-making.

For more information please check out our [website](https://dara.causalens.com/) and [documentation](https://dara.causalens.com/docs/category/build-dara-apps). The documentation provides detailed information on how to use Dara, what each feature does, and potential applications. To further illustrate its capabilities, we also offer a set of [examples and use cases](https://github.com/causalens/dara_app_gallery). These examples demonstrate how the framework can be applied in different scenarios and give you a practical understanding of its potential. 

We value user feedback and continuously strive to improve our framework, so any suggestions or insights you can provide are highly appreciated.

Thank you for your interest, and we look forward to assisting you with any questions or issues you may have.

Kind Regards
