### ISSUE TITLE
Defining @action in class layout

### ISSUE THREAD

**Issue by Vlados09** [causalens/dara#164]
What is a recommended way of adding @actions in the class pages?

I have my variables and derived variables initialised in the `__init__` for full encapsulation but I am hitting a problem when trying to define an action

Have something like this:
```python
class Page:
    some_service: Service

    variable: Variable
    derived_variable: DerivedVariable

    def __init__(self, some_service: Service):
        self.some_service = some_service

        self.variable = Variable(default="default")

        self.derived_variable = DerivedVariable(
            func=self.some_service.get_derived_variable,
            variables=[self.variable],
        )

    @action
    async def reset_variable(self, ctx: action.Ctx, resolving_stage, selected_transaction):
        await ctx.update(variable=self.variable, value="")
 ```
 
 It doesnt like that there is a self in the function...
 
 Should it be something like this instead:
```python
variable = Variable(default="default")
  
@action
async def reset_variable(ctx: action.Ctx, resolving_stage, selected_transaction):
    await ctx.update(variable=self.variable, value="updated")

class Page:
    some_service: Service

    derived_variable: DerivedVariable

    def __init__(self, some_service: Service):
        self.some_service = some_service

        self.derived_variable = DerivedVariable(
            func=self.some_service.get_derived_variable,
            variables=[variable],
        )
 ```
 
 Its a bit annoying that I have to keep `Variable` and `DerivedVariable` defined separetly

**Comment by patricia-causalens** [comment]
Hi @Vlados09, thank you for reporting this! 
This is indeed a bug and we will look into fixing it, for the mean time you could write your page into functional form so that `Variable` and `DerivedVariable` can be kept together or do the approach you mentioned. Apologies for the inconvenience.
