### ISSUE TITLE
[doc demo debug]error in the document demo.

### ISSUE THREAD

**Issue by signup2k** [causalens/dara#288]
When I learned to use dara with documents, I found a bug (or typos) in the demo.

1.  demo at `Trigger`  https://dara.causalens.com/docs/generated/dara/docs/getting-started/actions#trigger
```
....
my_var = Variable(1)
der_var = DerivedVariable(lambda x: float(x) ** 2 , variables=[my_var], deps=[])

@action
async def trigger_my_var(ctx: action.Ctx):
    await ctx.trigger(variable=my_var).  # <- here!!, my_var --should be --> der_var
....
```

2. demo at  `Handling Data/Usage`
https://dara.causalens.com/docs/generated/dara/docs/getting-started/handling-data#usage

in "in a py_component" demo
```
import pandas
from bokeh import figure  # <- here!!! , shoud be -> from bokeh.plotting import figure

from dara.core import py_component, DataVariable, CacheType
from DerivedVariable import Table, Bokeh # <- here !!!, shoud be --> from dara.components import Table, Bokeh
....
````

3. demo at `Handling Data/Filtering`

https://dara.causalens.com/docs/generated/dara/docs/getting-started/handling-data#filtering

```
...

filtered_tables = Stack(
    Table(variable_filtered_1, columns=['a', 'b']),   # <- here !!!, shoud be --> Table(data = variable_filtered_1, columns=['a', 'b'])
    Table(variable_filtered_2, columns=['a', 'b'])  # <- here !!!, shoud be -->Table(data=variable_filtered_1, columns=['a', 'b'])
)
```

**Comment by patricia-causalens** [comment]
Hi @signup2k,

Thank you for finding these, I have made a PR addressing the issues you found.

Thanks again for checking out dara and do let us know if you have any more feedback!
