### ISSUE TITLE
`Select` seems still sluggish with large number of items, and does not work with `multiselect=True`

### ISSUE THREAD

**Issue by signup2k** [causalens/dara#307]
I have updated dara-core and dara-components
  - Updating dara-core (1.8.6 -> 1.9.4)
  - Updating dara-components (1.8.6 -> 1.9.4)
 
In windows, I get this with `multiselect=True`
<img width="472" alt="image" src="https://github.com/causalens/dara/assets/34048875/e0936a2b-f508-41d8-9fd0-75f167e52233">

and In M3 Chip MacOS，`Select` with large number of items still very sluggish. But the multiselect worked fine.

```
            Select(
                items=[Item(label=f'label{i}',value=f'value{i}') for i in range(11000)],
                searchable=True, multiselect=True, 
            )
```

![recording](https://github.com/causalens/dara/assets/34048875/c23d6dae-cfa2-480e-9135-0dd7b9f3ddd0)

**Comment by patricia-causalens** [comment]
Hi @signup2k,

Would you be able to let us know which browser you are using on Windows? Also could you share with us the error message you encountered, if you could open your developer tools and select the console tab, does it show any error messages? 

These would help us to pin point the issue more easily. Thank you for bringing it to our attention!

**Comment by signup2k** [comment]
Thanks for ur quickly replying @patricia-causalens 

I use chrome in Windows, and Arc in MacOS

The `Select` failing rendering with `multiselect=True` in windows Chrome Console 

![image](https://github.com/causalens/dara/assets/34048875/c6d793e6-80f5-4525-8b3c-7154d1bb2eed)

**Comment by Roman-Kornev** [comment]
Hey @signup2k. Thanks a lot for reporting the issues. Both should be fixed in the next release.

As part of that effort, the performance of not only Multiselect, but all other list-like components was increased significantly so they don't re-render unnecessarily.

Your feedback really helped us make these improvements for handling larger datasets.

Thanks again for your help!

**Comment by Roman-Kornev** [comment]
@signup2k Dara version `1.9.5` is now released to address these issues. Let me know if it worked for you or if there are any issues encounered. 

Thanks again!
