### ISSUE TITLE
Doesn't want to install with Poetry and python 3.12.4

### ISSUE THREAD

**Issue by matthiasautrata** [causalens/dara#325]
It seems that the package explicitly requires <= 3.12

**Comment by krzysztof-causalens** [comment]
Hello,

Thanks for reporting the issue. Indeed we currently cap the Python version, the highest version we've tested Dara on (and the one we use it on internally at the moment) is 3.11. 
We will look into relaxing and removing the version cap in the next few weeks once we get around to testing Dara out on 3.12 properly.

**Comment by Roman-Kornev** [comment]
Hey @matthiasautrata. We've released dara `v1.11.0`, which now supports Python 3.12. Feel free to try it. Let us know if you encounter any issues.
