### ISSUE TITLE
error create app

### ISSUE THREAD

**Issue by bobwatcherx** [causalens/dara#72]
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/dara# python3 --version
Python 3.10.12

error this
```

root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/dara# create-dara-app
  [1/7] project_name (Decision App): mydara
  [2/7] author_name (Author <author@example.com>): 

Project generated. Running post-generation hooks...
/home/miop/belajar/dara/mydara
Installing dependencies...
Creating virtualenv mydara in /home/miop/belajar/dara/mydara/.venv
Updating dependencies
Resolving dependencies... (3.1s)

  ConnectionError

  ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

  at /usr/local/lib/python3.10/dist-packages/requests/adapters.py:501 in send
      497│                 chunked=chunked,
      498│             )
      499│ 
      500│         except (ProtocolError, OSError) as err:
    → 501│             raise ConnectionError(err, request=request)
      502│ 
      503│         except MaxRetryError as e:
      504│             if isinstance(e.reason, ConnectTimeoutError):
      505│                 # TODO: Remove this in 3.0.0: see #2811
Error: Poetry install failed
ERROR:cookiecutter.generate:Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by bobwatcherx** [comment]
my conection internet is stable

but still error for create-dara-app

my info pc 
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/dara# uname -r
5.15.0-41-generic

root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/dara# cpuinfo 
Python Version: 3.10.12.final.0 (64 bit)
Cpuinfo Version: 9.0.0
Vendor ID Raw: GenuineIntel

AND MY OS is Linux Mint 


```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/dara# create-dara-app 
  [1/7] project_name (Decision App): ppp1
  [2/7] author_name (Author <author@example.com>): 

Project generated. Running post-generation hooks...
/home/miop/belajar/dara/ppp1
Installing dependencies...
Creating virtualenv ppp1 in /home/miop/belajar/dara/ppp1/.venv
Updating dependencies
Resolving dependencies... (5.0s)

  ConnectionError

  ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

  at /usr/local/lib/python3.10/dist-packages/requests/adapters.py:501 in send
      497│                 chunked=chunked,
      498│             )
      499│ 
      500│         except (ProtocolError, OSError) as err:
    → 501│             raise ConnectionError(err, request=request)
      502│ 
      503│         except MaxRetryError as e:
      504│             if isinstance(e.reason, ConnectTimeoutError):
      505│                 # TODO: Remove this in 3.0.0: see #2811
Error: Poetry install failed
ERROR:cookiecutter.generate:Stopping generation because post_gen_project hook script didn't exit successfully

```

**Comment by bobwatcherx** [comment]
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/dara# poetry --version
Poetry version 1.1.12

root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/dara# python3 --version
Python 3.10.12

**Comment by bobwatcherx** [comment]
i upgrade and installl
`pip install create-dara-app --upgrade`

**Comment by krzysztof-causalens** [comment]
Thanks for providing the details.
Based on your logs provided, it is most likely this is a `Poetry`-related issue. I can see you're on version `1.1.12` which is 2 years old at this point and could be the culprit - I was not able to reproduce your issue with newer poetry versions. 

From our side, the `create-dara-app` CLI simply scaffolds a project then runs `poetry install` within the new folder (or pip install if using a different packaging setting). You can skip the step by running `create-dara-app --no-install`. [More details about the CLI can be found on our docs page](https://dara.causalens.com/docs/generated/dara/docs/packages/create-dara-app/introduction). The only interaction with Poetry from our side is the `pyproject.toml` we generate, which perhaps is not compatible with your old Poetry version.

For further troubleshooting I would recommend upgrading the Poetry version used. If that doesn't help, I would suggest generating the project with the `--no-install` flag and then attempting to manually install the project. Alternatively you can use the `pip` packaging option, [refer to the CLI docs for details](https://dara.causalens.com/docs/generated/dara/docs/packages/create-dara-app/introduction#bootstrap).

**Comment by krzysztof-causalens** [comment]
Closing the issue for inactivity and because it is not really actionable on our part. Feel free to report if you have other issues with the CLI.
